version: "3"

services:
  api_server:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: api_server
    container_name: api_server
    ports: 
      - 8080:8080
    links:
      - db
    command: bash -c "bash ./wait-for-it.sh db:5432 -q -- diesel setup && cargo run --release"
    networks:
      - apinetwork

  db:
    image: postgres:9
    ports: 
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: supersecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - apinetwork

networks:
  apinetwork:
    driver: bridge
